### ISSUE TITLE
Max recursion depth exceeded

### ISSUE THREAD

**Issue by RobbertDM** [EqualExperts/dbt-unit-testing#132]
Hey there,

I could do `dbt run` and everything ran fine, then I installed this package (running `dbt clean` and `dbt deps`), then I ran `dbt run` again and I got a `max recursion depth exceeded` from python.

I'm not 100% sure yet, but my hypothesis is that it's because we have a `seeds.yml` file in which there's some text `ref('simple_table')` , and I think that messes with the `dbt-unit-testing` framework. Something to do with this part here: https://hub.getdbt.com/equalexperts/dbt_unit_testing/latest/#database-dependencies-in-detail

I'll try to make a reproducible example but I wanted to drop this here already so I don't forget.

PS: absolutely beautiful package, thanks for that!

**Comment by RobbertDM** [comment]
Possibly relevant stack trace pieces:
```
    if self.has_var(var_name):
  File "~/.local/lib/python3.10/site-packages/dbt/context/base.py", line 159, in has_var
    return var_name in self._merged
  File "~/.local/lib/python3.10/site-packages/dbt/utils.py", line 605, in __contains__
    return any((name in entry for entry in self._itersource()))
RecursionError: maximum recursion depth e
```

```
    return self.call_macro(*args, **kwargs)
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 258, in call_macro
    return macro(*args, **kwargs)
  File "/home/robbert/.local/lib/python3.10/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 2, in template
  File "/home/robbert/.local/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/context/base.py", line 170, in __call__

```

```
[0m15:26:14.715790 [error] [MainThread]: Encountered an error:
maximum recursion depth exceeded
[0m15:26:14.741222 [error] [MainThread]: Traceback (most recent call last):
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/main.py", line 136, in main
    results, succeeded = handle_and_check(args)
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/main.py", line 206, in handle_and_check
    task, res = run_from_args(parsed)
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/main.py", line 253, in run_from_args
    results = task.run()
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/task/runnable.py", line 454, in run
    self._runtime_initialize()
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/task/runnable.py", line 165, in _runtime_initialize
    super()._runtime_initialize()
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/task/runnable.py", line 94, in _runtime_initialize
    self.load_manifest()
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/task/runnable.py", line 81, in load_manifest
    self.manifest = ManifestLoader.get_full_manifest(self.config)
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 206, in get_full_manifest
    manifest = loader.load()
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 359, in load
    self.parse_project(
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/parser/manifest.py", line 466, in parse_project
    parser.parse_file(block, dct=dct)
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/parser/schemas.py", line 504, in parse_file
    self.parse_tests(test_block)
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/parser/schemas.py", line 475, in parse_tests
    self.parse_test(block, test, None)
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/parser/schemas.py", line 468, in parse_test
    self.parse_node(block)
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/parser/schemas.py", line 409, in parse_node
    node = self._parse_generic_test(
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/parser/schemas.py", line 338, in _parse_generic_test
    self.render_test_update(node, config, builder, schema_file_id)
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/parser/schemas.py", line 397, in render_test_update
    get_rendered(node.raw_code, context, node, capture_macros=True)
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 592, in get_rendered
    return render_template(template, ctx, node)
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 547, in render_template
    return template.render(ctx)
  File "/home/robbert/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/robbert/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/home/robbert/.local/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 331, in __call__
    return self.call_macro(*args, **kwargs)
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 258, in call_macro
    return macro(*args, **kwargs)
  File "/home/robbert/.local/lib/python3.10/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 12, in template
  File "/home/robbert/.local/lib/python3.10/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
  File "/home/robbert/.local/lib/python3.10/site-packages/dbt/clients/jinja.py", line 331, in __call__
```

**Comment by psousa50** [comment]
Hi @RobbertDM, apologies for the delayed response. Are you still facing the issue you mentioned earlier? If you are, could you kindly let me know the versions of dbt and Python you are using? I recall there might have been a compatibility issue between dbt and Python 3.10 at one point, so I just want to confirm if that might be the case here. I'll do my best to assist you further and resolve the issue.

**Comment by RobbertDM** [comment]
Ah okay. I haven't encountered the issue anymore. Running dbt 1.5.0 and python 3.10.6 atm, no clue what I was running back in April (but definitely python 3.10 looking at the stack trace).

Let's close the issue, I'll open a new one / reopen if we run into trouble again.
